import { describe, expect, it } from "vitest";
import {
  base64UrlEncode,
  buildTheoremreachEntryUrl,
  isTheoremreachPostbackEnabled,
  isTheoremreachWallConfigured,
  THEOREMREACH_CURRENCY_PLURAL,
  THEOREMREACH_CURRENCY_SINGULAR,
  THEOREMREACH_ENTRY_BASE_URL,
  THEOREMREACH_EXCHANGE_RATE,
  theoremreachEntryHash,
} from "../server";

const UID = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
const TXN = "11111111-2222-3333-4444-555555555555";
const TEST_KEY = "TESTAPPKEY";
const TEST_SECRET = "test-theoremreach-secret-key-abc123";
const TEST_PLACEMENT = "TESTPLACEMENT";

// Independent HMAC-SHA1 vector cross-checked with Python's hmac/hashlib
// (NOT generated by this implementation): secret + exact pre-hash URL below.
const EXPECTED_HASH = "kAKXUtYhpiUPW_bz3SgDB9r0CIw";
const EXPECTED_URL =
  "https://theoremreach.com/respondent_entry/direct?api_key=TESTAPPKEY&user_id=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee&transaction_id=11111111-2222-3333-4444-555555555555&currency_name_plural=cents&currency_name_singular=cent&exchange_rate=70&external_id=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee&partner_id=TESTPLACEMENT&hash=kAKXUtYhpiUPW_bz3SgDB9r0CIw";

function withEnv(vars: Record<string, string | undefined>, fn: () => void) {
  const prev: Record<string, string | undefined> = {};
  for (const k of Object.keys(vars)) prev[k] = process.env[k];
  try {
    for (const [k, v] of Object.entries(vars)) {
      if (v === undefined) delete process.env[k];
      else process.env[k] = v;
    }
    fn();
  } finally {
    for (const k of Object.keys(vars)) {
      if (prev[k] === undefined) delete process.env[k];
      else process.env[k] = prev[k] as string;
    }
  }
}

const FULL_ENV = {
  THEOREMREACH_API_KEY: TEST_KEY,
  THEOREMREACH_SECRET_KEY: TEST_SECRET,
  THEOREMREACH_PLACEMENT_ID: TEST_PLACEMENT,
  THEOREMREACH_POSTBACK_ENABLED: "true",
};

describe("TheoremReach server configuration (fail closed)", () => {
  it("wall unavailable unless api key + secret + placement all exist", () => {
    withEnv(
      { THEOREMREACH_API_KEY: undefined, THEOREMREACH_SECRET_KEY: undefined, THEOREMREACH_PLACEMENT_ID: undefined },
      () => expect(isTheoremreachWallConfigured()).toBe(false)
    );
    withEnv({ ...FULL_ENV, THEOREMREACH_SECRET_KEY: undefined }, () =>
      expect(isTheoremreachWallConfigured()).toBe(false)
    );
    withEnv(FULL_ENV, () => expect(isTheoremreachWallConfigured()).toBe(true));
  });

  it("postback master switch must be exactly true", () => {
    withEnv(FULL_ENV, () => expect(isTheoremreachPostbackEnabled()).toBe(true));
    withEnv({ ...FULL_ENV, THEOREMREACH_POSTBACK_ENABLED: "1" }, () =>
      expect(isTheoremreachPostbackEnabled()).toBe(false)
    );
    withEnv({ ...FULL_ENV, THEOREMREACH_POSTBACK_ENABLED: undefined }, () =>
      expect(isTheoremreachPostbackEnabled()).toBe(false)
    );
  });
});

describe("TheoremReach entry URL builder (server-only)", () => {
  it("uses the documented direct-entry base and publisher constants", () => {
    expect(THEOREMREACH_ENTRY_BASE_URL).toBe("https://theoremreach.com/respondent_entry/direct");
    expect(THEOREMREACH_EXCHANGE_RATE).toBe(70);
    expect(THEOREMREACH_CURRENCY_SINGULAR).toBe("cent");
    expect(THEOREMREACH_CURRENCY_PLURAL).toBe("cents");
  });

  it("produces the exact independently-verified signed URL", () => {
    withEnv(FULL_ENV, () => {
      expect(buildTheoremreachEntryUrl({ userId: UID, transactionId: TXN })).toBe(EXPECTED_URL);
    });
  });

  it("inserts the session UUID as user_id and preserves oid-style params", () => {
    withEnv(FULL_ENV, () => {
      const url = new URL(buildTheoremreachEntryUrl({ userId: UID, transactionId: TXN }));
      expect(url.searchParams.get("user_id")).toBe(UID);
      expect(url.searchParams.get("transaction_id")).toBe(TXN);
      expect(url.searchParams.get("partner_id")).toBe(TEST_PLACEMENT);
      expect(url.searchParams.get("api_key")).toBe(TEST_KEY);
      expect(url.searchParams.get("hash")).toBe(EXPECTED_HASH);
    });
  });

  it("mints a fresh transaction_id per entry URL by default", () => {
    withEnv(FULL_ENV, () => {
      const a = new URL(buildTheoremreachEntryUrl({ userId: UID }));
      const b = new URL(buildTheoremreachEntryUrl({ userId: UID }));
      expect(a.searchParams.get("transaction_id")).toMatch(
        /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
      );
      expect(a.searchParams.get("transaction_id")).not.toBe(b.searchParams.get("transaction_id"));
    });
  });

  it("hash changes when the signed URL changes (tamper-evident)", () => {
    withEnv(FULL_ENV, () => {
      const h1 = theoremreachEntryHash("https://x.example/a?b=1");
      const h2 = theoremreachEntryHash("https://x.example/a?b=2");
      expect(h1).not.toBe(h2);
    });
  });

  it("URL-safe Base64: no +, /, =, or newlines", () => {
    // 0xfb 0xff bytes classically produce + and / in standard Base64.
    const encoded = base64UrlEncode(new Uint8Array([251, 255, 190, 254, 0, 128]));
    expect(encoded).toMatch(/^[A-Za-z0-9\-_]+$/);
    expect(encoded).not.toContain("+");
    expect(encoded).not.toContain("/");
    expect(encoded).not.toContain("=");
    expect(encoded).not.toContain("\n");
  });

  it("raw Secret Key never appears in the generated URL", () => {
    withEnv(FULL_ENV, () => {
      const built = buildTheoremreachEntryUrl({ userId: UID, transactionId: TXN });
      expect(built).not.toContain(TEST_SECRET);
    });
  });

  it("fails closed without configuration or userId", () => {
    withEnv({ ...FULL_ENV, THEOREMREACH_SECRET_KEY: undefined }, () =>
      expect(() => buildTheoremreachEntryUrl({ userId: UID })).toThrow()
    );
    withEnv(FULL_ENV, () => expect(() => buildTheoremreachEntryUrl({ userId: "" })).toThrow());
  });
});
